### ISSUE TITLE
Motion Watcher Setup

### ISSUE THREAD

**Issue by ryanlaux** [ShinobiOtaku/WeMoService#1]
Would you mind giving a few pointers on how to get this code up a running? Been trying to integrate my motion sensors into my automation setup and you're project it the only I've found that uses the ouimeaux code in its own script.

Specifically I'm looking to send a simple http rest call when motion is triggered.

Any help would be appreciated!

**Comment by ShinobiOtaku** [comment]
I'm impressed you even found this project, it's one of my old home automation projects that never really got the love and attention it deserved.

Anyway.

There's not a lot to it really, ouimeaux does all the hard work and all you have to do is be connected to the same wifi network and your sensor.

You could just take my code and strip out all of the rabbitmq stuff and go from there, or there's some handy documentation here: https://ouimeaux.readthedocs.org/en/latest/

Your question is a little vague so it's hard to help anymore than that, let me know if I can help with anything specifically.

**Comment by ryanlaux** [comment]
Thanks for reaching out! yeah I just did a github search for wemo motion and yours was one of the only projects that came up. I'm trying to get the motion integrated with home-assistant, which is a python based home automaton server with uses various libraries to control different devices. 
https://github.com/balloob/home-assistant

The wemo component is sourced by this project:
https://github.com/pavoni/pywemo

And I've been talking to the dev there to try to get something working. Maybe you could shed some insight as how to read the state information from the motion? We have an issue thread going here: https://github.com/pavoni/pywemo/issues/31

Any help would be greatly appreciated! I feel like not many people have wemo motion's meanwhile I have 2 sitting around!

**Comment by ShinobiOtaku** [comment]
It looks awfully like pavoni's version is stripped down to be query based only, whereas mine is event driven so getting the state out of it would be completely different.

Either way, the other issue is closed now so it looks like you've got to the bottom of it :+1:

**Comment by ryanlaux** [comment]
Yeah, I ran a test with him and was able to get state read from the motion,
he's going to play with the code and see how he can get it working with our
automation server.

Might still try to pick apart your code if the other solution isn't robust
enough. Would probably run as a helper app/ bridge just to receive motion
event and send a http command to the server. Will let you know if I need
any help with that.

Thanks!!
